Initial commit for version 2.0.x patch release

diff --git a/Allwmake b/Allwmake
--- a/Allwmake
+++ b/Allwmake
@@ -1,13 +1,18 @@
 #!/bin/sh
 cd ${0%/*} || exit 1    # run from this directory
 
-if [ "$PWD" != "$WM_PROJECT_DIR" ]
-then
+wmakeCheckPwd "$WM_PROJECT_DIR" || {
     echo "Error: Current directory is not \$WM_PROJECT_DIR"
-    echo "    The environment variable are not consistent with the installation."
+    echo "    The environment variables are inconsistent with the installation."
     echo "    Check the OpenFOAM entries in your dot-files and source them."
     exit 1
-fi
+}
+
+[ -n "$FOAM_EXT_LIBBIN" ] || {
+    echo "Error: FOAM_EXT_LIBBIN not set"
+    echo "    Check the OpenFOAM entries in your dot-files and source them."
+    exit 1
+}
 
 # wmake is required for subsequent targets
 ( cd wmake/src && make )
@@ -15,7 +20,9 @@ fi
 # build ThirdParty sources
 if [ -d "$WM_THIRD_PARTY_DIR" ]
 then
-    ( cd $WM_THIRD_PARTY_DIR && ./Allwmake )
+    $WM_THIRD_PARTY_DIR/Allwmake
+else
+    echo "no ThirdParty sources found - skipping"
 fi
 
 # build OpenFOAM libraries and applications
diff --git a/bin/foamCleanPath b/bin/foamCleanPath
--- a/bin/foamCleanPath
+++ b/bin/foamCleanPath
@@ -1,11 +1,11 @@
 #!/bin/sh
-#---------------------------------*- sh -*-------------------------------------
+#------------------------------------------------------------------------------
 # =========                 |
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     |
-#   \\  /    A nd           | Copyright (C) 1991-2010 OpenCFD Ltd.
+#   \\  /    A nd           | Copyright (C) 2004-2011 OpenCFD Ltd.
 #    \\/     M anipulation  |
-#------------------------------------------------------------------------------
+#-------------------------------------------------------------------------------
 # License
 #     This file is part of OpenFOAM.
 #
@@ -31,45 +31,72 @@
 #     Prints its argument (which should be a ':' separated path)
 #     without all
 #         - duplicate elements
-#         - (if '-strip') non-accessible directories
 #         - elements whose start matches a wildcard
+#         - inaccessible directories (with the -strip (at your option)
 #
-#     Note:
-#         - this routine will fail when directories have embedded spaces
-#         - false matches possible if a wildcard contains '.' (sed regex)
+# Note
+#     - this routine will fail when directories have embedded spaces
+#     - false matches possible if a wildcard contains '.' (sed regex)
+#     - the wildcards can themselves can be written together and separated
+#       by colons or whitespace
 #------------------------------------------------------------------------------
-if [ "$#" -lt 1 -o "$1" = "-h" -o "$1" = "-help" ]
-then
-   cat <<USAGE 1>&2
-Usage: ${0##*/} [-strip] path [wildcard] .. [wildcard]
+usage() {
+    cat <<USAGE 1>&2
+Usage: ${0##*/} [OPTION] path [wildcard1] .. [wildcardN]
+options:
+  -strip            remove inaccessible directories
+  -help             print the usage
 
-    Prints its argument (which should be a ':' separated list) cleansed from
-      - duplicate elements
-      - elements whose start matches one of the wildcard(s)
-      - (if '-strip') non-accessible directories
+  Prints its argument (which should be a ':' separated list) cleansed from
+    - duplicate elements
+    - elements whose start matches one of the wildcard(s)
+    - inaccessible directories (with the -strip (at your option)
+
+  Exit status
+      0  on success
+      1  for miscellaneous errors.
+      2  initial value of 'path' is empty
+
 USAGE
-   exit 1
-fi
+    exit 1
+}
 
 
-strip=''
-if [ "$1" = "-strip" ]
-then
-    strip=true
-    shift
-fi
+unset strip
+# parse options
+while [ "$#" -gt 0 ]
+do
+    case "$1" in
+    -h | -help)
+        usage
+        ;;
+    -strip)
+        strip=true
+        shift
+        ;;
+    *)
+        break
+        ;;
+    esac
+done
 
+
+[ "$#" -ge 1 ] || usage
 
 dirList="$1"
 shift
 
+[ -n "$1" ] || exit 2    # quick exit on empty 'dirList'
+
+
 ##DEBUG echo "input>$dirList<" 1>&2
 
-# preserve current IFS and split on whitespace
+# preserve current IFS and split on colon or whitespace
 oldIFS="$IFS"
-IFS=' '
+IFS=': '
 
 # "wildcard1 ... wildcardN" may have been passed as a single parameter
+# or may contain ':' separators
 set -- $*
 
 # strip out wildcards via sed
@@ -78,7 +105,10 @@ do
     wildcard=$1
     shift
     ##DEBUG echo "remove>$wildcard<" 1>&2
-    dirList=`echo "$dirList" | sed -e "s@${wildcard}[^:]*:@@g"`
+    if [ -n "$wildcard" ]
+    then
+        dirList=$(echo "$dirList:" | sed -e "s@${wildcard}[^:]*:@@g")
+    fi
 done
 
 # split on ':' (and on space as well to avoid any surprises)
@@ -96,24 +126,24 @@ do
     if [ -e "$dir" ]
     then
         #- no duplicate dirs
-        duplicate=`echo " $dirList " | sed -ne "s@ $dir @DUP@p"`
+        duplicate=$(echo " $dirList " | sed -ne "s@ $dir @DUP@p")
 
         if [ ! "$duplicate" ]
         then
             dirList="$dirList $dir"
         fi
-    elif [ "$strip" != "true" ]
+    elif [ "$strip" != true ]
     then
         # Print non-existing directories if not in 'strip' mode.
         dirList="$dirList $dir"
     fi
 done
 
-# parse on whitespace
+# split on whitespace
 IFS=' '
 set -- $dirList
 
-# join on ':'
+# rejoin on ':'
 IFS=':'
 dirList="$*"
 
diff --git a/bin/foamCopySettings b/bin/foamCopySettings
--- a/bin/foamCopySettings
+++ b/bin/foamCopySettings
@@ -1,11 +1,11 @@
 #!/bin/sh
-#---------------------------------*- sh -*-------------------------------------
+#-------------------------------------------------------------------------------
 # =========                 |
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     |
-#   \\  /    A nd           | Copyright (C) 1991-2010 OpenCFD Ltd.
+#   \\  /    A nd           | Copyright (C) 2008-2011 OpenCFD Ltd.
 #    \\/     M anipulation  |
-#------------------------------------------------------------------------------
+#-------------------------------------------------------------------------------
 # License
 #     This file is part of OpenFOAM.
 #
@@ -31,19 +31,54 @@
 #     Copy OpenFOAM settings from one case to another, without copying
 #     the mesh or results
 #     - requires rsync
+#
+# Note
+#     The foamCopySettings.rc (found with the ~OpenFOAM expansion) can be used
+#     to add any custom rsync options.
+#-------------------------------------------------------------------------------
+Script=${0##*/}
+
 #------------------------------------------------------------------------------
-if [ "$1" = "-h" -o "$1" = "-help" -o "$#" -ne 2 ]
-then
-    cat <<USAGE 1>&2
-Usage: ${0##*/} srcDir dstDir
+usage() {
+    exec 1>&2
+    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
+    cat <<USAGE
+
+Usage: $Script srcDir dstDir
 
     Copy OpenFOAM settings from one case to another, without copying
     the mesh or results.
     - requires rsync
 
+Note
+    The $Script.rc (found via the ~OpenFOAM expansion - see foamEtcFile)
+    can be used to add any custom rsync options.
+
 USAGE
-   exit 1
-fi
+    exit 1
+}
+#------------------------------------------------------------------------------
+
+# parse options
+while [ "$#" -gt 0 ]
+do
+    case "$1" in
+    -h | -help)
+        usage
+        ;;
+    -*)
+        usage "unknown option: '$*'"
+        ;;
+    *)
+        break
+        ;;
+    esac
+done
+
+# need rsync
+type rsync >/dev/null 2>&1 || usage "Error: 'rsync' seems to be missing"
+
+[ "$#" -eq 2 ] || usage "Error: incorrect number of arguments"
 
 srcDir=${1%/}
 dstDir=${2%/}
@@ -65,12 +100,31 @@ do
 done
 
 # files and directories to copy
-# avoid processor directories
+# avoid processor directories here too to make for cleaner output
 fileList=$(find -H $srcDir -mindepth 1 -maxdepth 1 -not -name "processor*")
+
+# avoid polyMesh and processor* directories
+rsync="rsync --exclude polyMesh --exclude processor*"
+
+#
+# get any extra user options
+# extract lines starting with '--longOption'
+#
+if rcFile=$(foamEtcFile $Script.rc)
+then
+    rsync="$rsync "$(sed -ne '/^ *--/p' $rcFile | tr '\n' ' ')
+fi
+
 
 # TODO:
 #  - verify that it works with multiple mesh regions
 #  - special treatment for starting with negative crank angles
+
+
+echo
+echo "synchronizing with"
+echo "    $rsync"
+echo
 
 for i in $fileList
 do
@@ -78,15 +132,20 @@ do
     # skip numerical (results) directories (except 0)
     # and things that look like log files or queuing system output
     case "$name" in
-    [1-9] | [0-9]?* | log | *.log | foam.[eo][1-9]* )
+    ( [1-9] | [0-9]?* | log | *.log | foam.[eo][1-9]* )
         echo "$i  [skipped]"
         continue
         ;;
-    *)
+    # skip things that look sampled directories and converted data
+    ( probes | sets | surfaces | En[Ss]ight )
+        echo "$i  [skipped]"
+        continue
+        ;;
+    (*)
         echo "$i -> $dstDir/$name"
-        rsync --exclude polyMesh --exclude "processor*" -a $i $dstDir
+        $rsync -a $i $dstDir
         ;;
     esac
 done
 
-# --------------------------------------------------------------- end-of-file
+# ------------------------------------------------------------------ end-of-file
diff --git a/bin/foamExec b/bin/foamExec
--- a/bin/foamExec
+++ b/bin/foamExec
@@ -3,7 +3,7 @@
 # =========                 |
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     |
-#   \\  /    A nd           | Copyright (C) 1991-2010 OpenCFD Ltd.
+#   \\  /    A nd           | Copyright (C) 2004-2011 OpenCFD Ltd.
 #    \\/     M anipulation  |
 #-------------------------------------------------------------------------------
 # License
@@ -31,23 +31,35 @@
 #     Runs the <foamVersion> version of executable <foamCommand>
 #     with the rest of the arguments.
 #
-#     Can also be used for parallel runs e.g.
-#     mpirun -np <nProcs> \
-#         foamExec -v <foamVersion> <foamCommand> ... -parallel
+#     Can also be used for parallel runs. For example,
+#     \code
+#         mpirun -np <nProcs> \
+#             foamExec -version <foamVersion> <foamCommand> ... -parallel
+#     \endcode
+#
+# Note
+#     This script must exist in <foamInstall>/OpenFOAM-<VERSION>/bin/
+#     or <foamInstall>/openfoam<VERSION>/bin/ (for the debian version)
+#
+#     foamEtcFile must be found in the same directory as this script
 #
 # SeeAlso
 #    foamEtcFile
+#
 #------------------------------------------------------------------------------
 usage() {
+    exec 1>&2
     while [ "$#" -ge 1 ]; do echo "$1"; shift; done
     cat<<USAGE
 
 Usage: ${0##*/} [OPTION] <application> ...
 
 options:
+  -prefix <dir>     specify an alternative installation prefix
+                    pass through to foamEtcFile and set as FOAM_INST_DIR
   -version <ver>    specify an alternative OpenFOAM version
                     pass through to foamEtcFile
-  -help             this usage
+  -help             print the usage
 
 * run a particular OpenFOAM version of <application>
 
@@ -55,12 +67,20 @@ USAGE
     exit 1
 }
 
-#
-# This script must exist in <foamInstall>/OpenFOAM-<VERSION>/bin/
-# or <foamInstall>/openfoam<VERSION>/bin/ (for the debian version)
-#
-# foamEtcFile must be found in the same directory as this script
 #-------------------------------------------------------------------------------
+
+# the bin dir:
+binDir="${0%/*}"
+
+# the project dir:
+projectDir="${binDir%/bin}"
+
+# the prefix dir (same as foamInstall):
+prefixDir="${projectDir%/*}"
+
+# # the name used for the project directory
+# projectDirName="${projectDir##*/}"
+
 
 unset etcOpts version
 # parse options
@@ -70,15 +90,21 @@ do
     -h | -help)
         usage
         ;;
-    -v | -version)
+    -m | -mode)
         [ "$#" -ge 2 ] || usage "'$1' option requires an argument"
-        version="$2"
         etcOpts="$etcOpts $1 $2"    # pass-thru to foamEtcFile
         shift
         ;;
-    -m | -mode | -p | -prefix)
+    -p | -prefix)
         [ "$#" -ge 2 ] || usage "'$1' option requires an argument"
         etcOpts="$etcOpts $1 $2"    # pass-thru to foamEtcFile
+        prefixDir="$2"
+        shift
+        ;;
+    -v | -version)
+        [ "$#" -ge 2 ] || usage "'$1' option requires an argument"
+        etcOpts="$etcOpts $1 $2"    # pass-thru to foamEtcFile
+        version="$2"
         shift
         ;;
     --)
@@ -95,22 +121,21 @@ do
     shift
 done
 
-
 #
 # Find and source OpenFOAM settings (bashrc)
 # placed in function to preserve command-line arguments
 #
 sourceRc()
 {
-    # default is the current version
-    : ${version:=${WM_PROJECT_VERSION:-unknown}}
-
-    foamDotFile="$(${0%/*}/foamEtcFile $etcOpts bashrc)" || {
-        echo "Error : bashrc file could not be found for OpenFOAM-$version" 1>&2
+    foamDotFile="$($binDir/foamEtcFile $etcOpts bashrc)" || {
+        echo "Error : bashrc file could not be found for OpenFOAM-${version:-${WM_PROJECT_VERSION:-???}}" 1>&2
         exit 1
     }
 
-    . $foamDotFile
+    # set to consistent value before sourcing the bashrc
+    export FOAM_INST_DIR="$prefixDir"
+
+    . $foamDotFile $FOAM_SETTINGS
 }
 
 
diff --git a/bin/foamJob b/bin/foamJob
--- a/bin/foamJob
+++ b/bin/foamJob
@@ -1,11 +1,11 @@
 #!/bin/sh
-#---------------------------------*- sh -*-------------------------------------
+#------------------------------------------------------------------------------
 # =========                 |
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     |
-#   \\  /    A nd           | Copyright (C) 1991-2010 OpenCFD Ltd.
+#   \\  /    A nd           | Copyright (C) 2004-2011 OpenCFD Ltd.
 #    \\/     M anipulation  |
-#------------------------------------------------------------------------------
+#-------------------------------------------------------------------------------
 # License
 #     This file is part of OpenFOAM.
 #
@@ -26,75 +26,67 @@
 #     foamJob
 #
 # Description
+#     Run an OpenFOAM job in background.
+#     Redirects the output to 'log' in the case directory.
 #
 #------------------------------------------------------------------------------
 usage() {
-   while [ "$#" -ge 1 ]; do echo "$1"; shift; done
-   cat<<USAGE
+    exec 1>&2
+    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
+    cat<<USAGE
 
-usage: ${0##*/} [OPTION] <application> ...
-
+Usage: ${0##*/} [OPTION] <application> ...
 options:
-  -case dir     specify case directory
-  -s            also sends output to screen
-  -p            parallel run of processors
-  -v ver        specify OpenFOAM version
-  -help         this usage
+  -case <dir>       specify alternative case directory, default is the cwd
+  -parallel         parallel run of processors
+  -screen           also sends output to screen
+  -version <ver>    specify an alternative OpenFOAM version
+  -help             print the usage
 
 * run an OpenFOAM job in background.
   Redirects the output to 'log' in the case directory
 
 USAGE
-   exit 1
+    exit 1
 }
 
 unset version
 
 # replacement for possibly buggy 'which'
 findExec() {
-   case "$1" in
-   */*)
-      if [ -x "$1" ] ; then
-         echo "$1"
-         return 0
-      fi
-      ;;
-   esac
+    case "$1" in
+    */*)
+        if [ -x "$1" ]
+        then
+            echo "$1"
+            return 0
+        fi
+        ;;
+    esac
 
-   oldIFS=$IFS
-   IFS=':'
-   for d in $PATH
-   do
-      # echo "testing: $d/$1" 1>&2
-      if [ -x "$d/$1" -a ! -d "$d/$1" ] ; then
-         # echo "Found exec: $d/$1" 1>&2
-         IFS=$oldIFS
-         echo "$d/$1"
-         return 0
-      fi
-   done
-   IFS=$oldIFS
-   echo ""
-   return 1
-}
-
-# grep for $1
-getPID() {
-   ps -u $LOGNAME -o 'pid,args' | fgrep "$1 " | fgrep -v grep | head -1 | awk '{ print $1 }'
+    oldIFS=$IFS
+    IFS=':'
+    for d in $PATH
+    do
+        # echo "testing: $d/$1" 1>&2
+        if [ -x "$d/$1" -a ! -d "$d/$1" ]
+        then
+            # echo "Found exec: $d/$1" 1>&2
+            IFS=$oldIFS
+            echo "$d/$1"
+            return 0
+        fi
+     done
+     IFS=$oldIFS
+     echo ""
+     return 1
 }
 
 
-consultGuide() {
-cat<<EOF
-
-Please consult the User Guide for details of parallel running
-EOF
-}
 
 # MAIN SCRIPT
 #~~~~~~~~~~~~
-SCREEN=no
-PARALLEL=no
+unset parallelOpt screenOpt
 
 
 # parse options
@@ -105,23 +97,22 @@ do
       usage
       ;;
    -case)
-      [ "$#" -ge 2 ] || usage "'-case' option requires an argument"
-      caseDir=$2
+      [ "$#" -ge 2 ] || usage "'$1' option requires an argument"
+      cd "$2" 2>/dev/null || usage "directory does not exist:  '$2'"
       shift 2
-      cd "$caseDir" 2>/dev/null || usage "directory does not exist:  '$caseDir'"
       ;;
-   -s)
-      SCREEN=yes
-      shift
-      ;;
-   -p)
-      PARALLEL=yes
+   -p | -parallel)
+      parallelOpt=true
       shift
       ;;
-   -v)
+   -s | -screen)
+      screenOpt=true
       shift
-      version=$1
-      shift
+      ;;
+   -v | -version)
+      [ "$#" -ge 2 ] || usage "'$1' option requires an argument"
+      version="$2"
+      shift 2
       ;;
    --)
       shift
@@ -136,100 +127,116 @@ do
    esac
 done
 
-if [ "$#" -lt 1 ]; then
-   usage "No application specified"
-fi
+[ "$#" -ge 1 ] || usage "No application specified"
 
-# use foamExec for a specified version and for remote (parallel) runs
-if [ -n "$version" -o "$PARALLEL" = yes ]; then
-   APPLICATION=`findExec foamExec`
-   if [ $? -ne 0 ]; then
-      usage "'foamExec' not found"
-   fi
-   if [ -n "$version" ]; then
-      APPLICATION="$APPLICATION -v $version"
-   fi
-else
-   APPLICATION=`findExec $1`
-   if [ $? -ne 0 ]; then
-      usage "Application '$1' executable not found"
-   fi
-   echo "Application : $1"
-   shift
-fi
 
-if [ "$PARALLEL" = no ]; then
-#
-#   RUN ON SINGLE PROCESSOR
-#
-    if [ "$SCREEN" = no ]; then
-       echo "Executing: $APPLICATION $@ > log 2>&1 &"
-       $APPLICATION $@ > log 2>&1 &
-    else
-       echo "Executing: $APPLICATION $@ | tee log &"
-       $APPLICATION $@ | tee log &
-       wait $!
+# use foamExec for a specified version
+# also need foamExec for remote (parallel) runs
+if [ -n "$version" -o "$parallelOpt" = true ]
+then
+    # when possible, determine if application even exists
+    if [ -z "$version" ]
+    then
+        findExec $1 >/dev/null || usage "Application '$1' not found"
     fi
+
+    # use foamExec for dispatching
+    APPLICATION=`findExec foamExec` || usage "'foamExec' not found"
+
+    [ -n "$version" ] && APPLICATION="$APPLICATION -version $version"
+
+    # attempt to preserve the installation directory 'FOAM_INST_DIR'
+    if [ -d "$FOAM_INST_DIR" ]
+    then
+        APPLICATION="$APPLICATION -prefix $FOAM_INST_DIR"
+    fi
+
 else
+    APPLICATION=`findExec $1` || usage "Application '$1' not found"
+    echo "Application : $1"
+    shift
+fi
 
-#
-#   IS THE CASE DECOMPOSED?
-#
-   if [ -r "processor0" ] ; then
-      NPROCS="`/bin/ls -1d processor* | wc -l`"
-   else
-      echo "Case is not currently decomposed"
-      if [ -r system/decomposeParDict ] ; then
-         echo "system/decomposeParDict exists"
-         echo "Try decomposing with \"foamJob decomposePar\""
-         exit 1
-      else
-         echo "Cannot find system/decomposeParDict file required to decompose the case for parallel running."
-         consultGuide
-         exit 1
-      fi
-   fi
-#
-#   LOCATE MPIRUN
-#
-   mpirun=`findExec mpirun`
-   if [ $? -ne 0 ]; then
-      usage "'mpirun' not found"
-   fi
-   mpiopts="-np $NPROCS"
 
-#
-#   IS THE MACHINE READY TO RUN PARALLEL?
-#
-   echo "Parallel processing using $WM_MPLIB with $NPROCS processors"
-   case "$WM_MPLIB" in
-   OPENMPI)
-      # add hostfile info
-      for hostfile in \
-         hostfile \
-         machines \
-         system/hostfile \
-         system/machines \
-      ;
-      do
-         if [ -r $hostfile ]; then
-            mpiopts="$mpiopts -hostfile $hostfile"
-            break
-         fi
-      done
-      ;;
-   esac
+if [ "$parallelOpt" = true ]
+then
+    # parallel
+    # ~~~~~~~~
 
-#
-#   RUN IN PARALLEL
-#
-   if [ "$SCREEN" = no ] ; then
-      echo "Executing: mpirun $mpiopts $APPLICATION $@ -parallel > log 2>&1"
-      $mpirun $mpiopts $APPLICATION $@ -parallel > log 2>&1 &
-   else
-      echo "Executing: mpirun $mpiopts $APPLICATION $@ -parallel | tee log"
-      $mpirun $mpiopts $APPLICATION $@ -parallel  | tee log
-   fi
+    #
+    # is the case decomposed?
+    #
+    if [ -r "processor0" ]
+    then
+        NPROCS="`/bin/ls -1d processor* | wc -l`"
+    else
+        echo "Case is not currently decomposed"
+        if [ -r system/decomposeParDict ]
+        then
+            echo "system/decomposeParDict exists"
+            echo "Try decomposing with \"foamJob decomposePar\""
+            exit 1
+        else
+            echo "Cannot find system/decomposeParDict file required to decompose the case for parallel running."
+            echo "Please consult the User Guide for details of parallel running"
+            exit 1
+        fi
+    fi
+
+    #
+    # locate mpirun
+    #
+    mpirun=`findExec mpirun` || usage "'mpirun' not found"
+    mpiopts="-np $NPROCS"
+
+    #
+    # is the machine ready to run parallel?
+    #
+    echo "Parallel processing using $WM_MPLIB with $NPROCS processors"
+    case "$WM_MPLIB" in
+    *OPENMPI)
+        # add hostfile info
+        for hostfile in \
+            hostfile \
+            machines \
+            system/hostfile \
+            system/machines \
+            ;
+        do
+            if [ -r $hostfile ]
+            then
+                mpiopts="$mpiopts -hostfile $hostfile"
+                break
+            fi
+        done
+        ;;
+    esac
+
+    #
+    # run (in parallel)
+    #
+    if [ "$screenOpt" = true ]
+    then
+        echo "Executing: $mpirun $mpiopts $APPLICATION $@ -parallel | tee log"
+        $mpirun $mpiopts $APPLICATION $@ -parallel | tee log
+    else
+        echo "Executing: $mpirun $mpiopts $APPLICATION $@ -parallel > log 2>&1"
+        $mpirun $mpiopts $APPLICATION $@ -parallel > log 2>&1 &
+    fi
+
+else
+    #
+    # run (on single processor)
+    #
+    if [ "$screenOpt" = true ]
+    then
+        echo "Executing: $APPLICATION $@ | tee log &"
+        $APPLICATION $@ | tee log &
+        wait $!
+    else
+        echo "Executing: $APPLICATION $@ > log 2>&1 &"
+        $APPLICATION $@ > log 2>&1 &
+    fi
 fi
 
 #------------------------------------------------------------------------------
diff --git a/bin/foamLog b/bin/foamLog
--- a/bin/foamLog
+++ b/bin/foamLog
@@ -1,11 +1,11 @@
 #!/bin/sh
-#---------------------------------*- sh -*-------------------------------------
+#------------------------------------------------------------------------------
 # =========                 |
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     |
-#   \\  /    A nd           | Copyright (C) 1991-2010 OpenCFD Ltd.
+#   \\  /    A nd           | Copyright (C) 2004-2011 OpenCFD Ltd.
 #    \\/     M anipulation  |
-#------------------------------------------------------------------------------
+#-------------------------------------------------------------------------------
 # License
 #     This file is part of OpenFOAM.
 #
@@ -31,98 +31,161 @@
 # Bugs
 #     -solution singularity not handled
 #------------------------------------------------------------------------------
+Script=${0##*/}
+toolsDir=${0%/*}/tools
+siteDir=${WM_PROJECT_SITE:-${WM_PROJECT_INST_DIR:-<unknown>}/site}
+userDir=$HOME/.OpenFOAM
 
-PROGDIR=`dirname $0`
-PROGNAME=`basename $0`
+usage() {
+    exec 1>&2
+    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
+    cat <<USAGE
 
-if [ -r $HOME/.${PROGNAME}.db ]; then
-    DBFILE=$HOME/.${PROGNAME}.db
-else
-    DBFILE=$PROGDIR/$PROGNAME.db
-fi
+Usage: $Script [OPTIONS] <log>
+  -list             lists but does not extract
+  -n                create single column files with the extracted data only
+  -quiet            quiet operation
+  -help             print the usage
 
+$Script - extracts xy files from OpenFOAM logs.
 
-printUsage() {
-cat <<LABUSAGE
-$PROGNAME - extracts xy files from Foam logs.
-
-Usage: $PROGNAME [-n][-s] <log>
-           extracts xy files from log
-       $PROGNAME -l <log>
-           lists but does not extract
-       $PROGNAME -h
-           for a help message
-
-LABUSAGE
+USAGE
+    exit 1
 }
 
+#------------------------------------------------------------------------------
 
 printHelp() {
-printUsage
-cat <<LABHELP
-The default is to extract for all the 'Solved for' variables the
-initial residual, the final residual and the number of iterations. On
-top of this a (user editable) database of standard non-solved for
-variables is used to extract data like Courant number, execution time.
+cat <<HELP
+-----------------------------------------------------------------------------
+The default is to extract for all the 'Solved for' variables the initial
+residual, the final residual and the number of iterations. Additionally, a
+(user editable) database is used to extract data for standard non-solved for
+variables like Courant number, and execution time.
 
-$PROGNAME -l shows all the possible variables but does not extract them.
+$Script -l lists all the possible variables without extracting them.
 
-The program will generate and run an awk script which writes a set of
-files, logs/<var>_<subIter>, for every <var> specified, for every
-occurrence inside a time step.
+The program will generate and run an awk script which writes a set of files,
+logs/<var>_<subIter>, for every <var> specified, for every occurrence inside
+a time step.
 
-For variables that are 'Solved for' the initial residual name will 
-be <var>, the final residual will get name <var>FinalRes,
+For variables that are 'Solved for', the initial residual name will be
+<var>, the final residual receive the name <var>FinalRes,
 
-The files are a simple xy format with the first column Time (default)
+The files are output in a simple xy format with the first column Time (default)
 and the second the extracted values. Option -n creates single column
 files with the extracted data only.
 
 
-The query database is a simple text format with three entries per line, 
-separated with '/'. Column 1 is the name of the variable (cannot contain
-spaces), column 2 is the extended regular expression (egrep) to select
-the line and column 3 is the string (fgrep) to select the column inside the
-line. The value taken will be the first (non-space)word after this
-column. The database will either be \$HOME/.${PROGNAME}.db or if not
-found  $PROGDIR/${PROGNAME}.db.
+The query database is a simple text format with three entries per line,
+separated with '/' :
+  Column 1 is the name of the variable (cannot contain spaces).
+  Column 2 is the extended regular expression (egrep) to select the line.
+  Column 3 is the string (fgrep) to select the column inside the line.
+The value taken will be the first (non-space)word after this column.
+The database ($Script.db) will taken from these locations:
 
-Option -s suppresses the default information and only prints the extracted
+    .
+    $userDir/$WM_PROJECT_VERSION
+    $userDir
+    $siteDir/$WM_PROJECT_VERSION
+    $siteDir
+    $WM_PROJECT_DIR/etc
+    $toolsDir
+
+Option -q suppresses the default information and only prints the extracted
 variables.
+-----------------------------------------------------------------------------
+HELP
 
-LABHELP
+usage
 }
 
 
+timeName=Time
+unset listOpt quietOpt
 
-myEcho() {
-  if [ "$VERBOSE" ]; then
-      echo "$*"
-  fi
+# parse options
+while [ "$#" -gt 0 ]
+do
+    case "$1" in
+    -h | -help)
+        printHelp
+        exit 0
+        ;;
+    -n)
+        unset timeName
+        shift
+        ;;
+    -l | -list)
+        listOpt=true
+        shift
+        ;;
+    -q | -quiet | -s | -silent)
+        quietOpt=true
+        shift
+        ;;
+    -*)
+        usage "unknown option: '$*'"
+        ;;
+    *)
+        break
+        ;;
+    esac
+done
+
+# find the database file
+DBFILE=$Script.db
+[ -f $DBFILE ] || DBFILE=`foamEtcFile $Script.db` || DBFILE=$toolsDir/$Script.db
+
+# need the database file
+[ -f $DBFILE ] || {
+    echo "$Script: Cannot read database $DBFILE"
+    exit 1
 }
+
+# single logFile
+if [ $# -eq 1 ]
+then
+    LOG=$1
+    [ -r "$LOG" ] && [ -f "$LOG" ] || usage "Cannot read log $LOG"
+else
+    usage
+fi
+
+
+myEcho()
+{
+   [ "$quietOpt" = true ] || echo "$*"
+}
+
 
 # getSolvedVars logFile
 # Prints names of all 'solved for' variables in the log file.
-getSolvedVars() {
+getSolvedVars()
+{
     fgrep ' Solving for ' $1 | fgrep ',' | sed -e 's/.* Solving for \([^,]*\)[,:].*/\1/' | sort -u
 }
 
 
 # getQueries dbFile queryName
 # Gets regular expressions for a certain queryName from the database
-getQueries() {
-    if [ ! -f "$1" ]; then
-        echo "Cannot find dbFile $1"
-        exit 1
-    fi
-
+getQueries()
+{
+    dbFile=$1
     queryName=$2
 
-    LINEQ=`grep -v '^#' $1 | awk -F '/' "/$queryName/ {if (\"$queryName\" "'!= $1) next; print $2}'`
-    NUMQ=`grep -v '^#' $1 | awk -F '/' "/$queryName/ {if (\"$queryName\" "'!= $1) next; print $3}'`
+    [ -f "$dbFile" ] || {
+        echo "Cannot find dbFile $dbFile"
+        exit 1
+    }
+
+    LINEQ=`grep -v '^#' $dbFile | awk -F '/' "/$queryName/ {if (\"$queryName\" "'!= $1) next; print $2}'`
+    NUMQ=`grep -v '^#' $dbFile | awk -F '/' "/$queryName/ {if (\"$queryName\" "'!= $1) next; print $3}'`
 
     #echo "For $queryName found line selection /$LINEQ/ , column selection /$NUMQ/" 1>&2
-    #if [ ! "$LINEQ" -o ! "$NUMQ" ]; then
+    #if [ ! "$LINEQ" -o ! "$NUMQ" ]
+    #then
     #    echo "Did not find query for $2 in database $1" 1>&2
     #fi
 }
@@ -130,14 +193,16 @@ getQueries() {
 
 # getDbQueryList dbFile
 # Echoes list of possible queries
-getDbQueryList() {
+getDbQueryList()
+{
     grep -v '^#' $1 | grep '[^ \t]' | awk -F '/' '{print $1}'
 }
 
 
 # getSolveQueryList logFile
 # Echoes list of queries from "solved for" variables in log file
-getSolveQueryList() {
+getSolveQueryList()
+{
     solvedVars=`getSolvedVars $1`
 
     for var in $solvedVars
@@ -148,9 +213,11 @@ getSolveQueryList() {
     done
 }
 
+
 # getAllQueries dbFile logFile
 # Gets all queries from database and from logfile
-getAllQueries() {
+getAllQueries()
+{
     #-- All solved for queries from log file
     queries=`getSolveQueryList $2`
 
@@ -163,9 +230,11 @@ getAllQueries() {
     do
         getQueries $1 "$var"
         line=`egrep "$LINEQ" $2`
-        if [ "$line" ]; then
+        if [ "$line" ]
+        then
             column=`echo "$line" | fgrep "$NUMQ"`
-            if [ "$column" ]; then
+            if [ "$column" ]
+            then
                 queries="$queries $var"
             fi
         fi
@@ -177,97 +246,38 @@ getAllQueries() {
     done | sort -u
 }
 
+
 #-----------------------------
 # Main
 #-----------------------------
 
-# sort arguments
-TIMENAME='Time'
-VERBOSE='yes'
-LISTONLY=''
-
-while getopts nslh flags
-do
-    case $flags in
-        n)  TIMENAME=""
-            ;;
-        h)  printHelp
-            exit 0
-            ;;
-        s)  VERBOSE=""
-            ;;
-        l)  LISTONLY='yes'
-            ;;
-	    \?) printUsage
-            exit 1
-            ;;
-    esac
-done
-
-
-# Shift options
-shift `expr $OPTIND - 1`
-
-if [ ! -f $DBFILE ]; then
-    echo "$PROGNAME: Cannot read database $DBFILE"
-    exit 1
-fi
-
-if [ "$LISTONLY" ]; then
-    if [ $# -ne 1 ]; then
-        printUsage
-        exit 1
-    fi
-    LOG=$1;
-    if [ ! -r $LOG ]; then
-        echo "$PROGNAME: Cannot read log $LOG"
-        exit 1
-    fi
+if [ "$listOpt" = true ]
+then
     getAllQueries $DBFILE $LOG
     exit 0
 fi
 
-if [ $# -ne 1 ]; then
-    printUsage
-    exit 1
-fi
+caseDir=.
+outputDir=$caseDir/logs
 
-CASEDIR=.
-LOG=$1
-if [ ! -r $LOG ]; then
-    echo "$PROGNAME: Cannot read log $LOG"
+[ -d "$caseDir" ] || {
+    echo "$Script: Cannot read $caseDir"
     exit 1
-fi
+}
 
 QUERYNAMES=`getAllQueries $DBFILE $LOG`
 
-
-if [ ! "$CASEDIR" ]; then
-    printUsage
-    exit 1
-fi
-
-if [ ! -d "$CASEDIR" ]; then
-    echo "$PROGNAME: Cannot read $CASEDIR"
-    exit 1
-fi
-
-if [ ! -f "$LOG" ]; then
-    echo "$PROGNAME: Cannot read log file $LOG"
-    exit 1
-fi
-
-
-#-- Make logs dir in case directory and put awk file there.
-
-mkdir -p $CASEDIR/logs
-AWKFILE=$CASEDIR/logs/$PROGNAME.awk
+#
+# Make logs dir in case directory and place awk file there
+#
+mkdir -p $outputDir
+AWKFILE=$outputDir/$Script.awk
 
 myEcho "Using:"
 myEcho "  log      : $LOG"
 myEcho "  database : $DBFILE"
 myEcho "  awk file : $AWKFILE"
-myEcho "  files to : $CASEDIR/logs"
+myEcho "  files to : $outputDir"
 myEcho ""
 
 
@@ -275,24 +285,25 @@ myEcho ""
 # Generate Awk program
 #-----------------------------
 
+rm -f $AWKFILE 2> /dev/null
+cat << AWK_CONTENTS > $AWKFILE
+# header
+BEGIN {
+    Iteration=0
+    resetCounters()
+}
 
+# reset counters used for variable postfix
+function resetCounters() {
+AWK_CONTENTS
+# ----------
 
-#-- header
-
-rm -f $AWKFILE; touch $AWKFILE
-echo "BEGIN {" >> $AWKFILE
-echo "    Iteration=0" >> $AWKFILE
-echo "    resetCounters()" >> $AWKFILE
-echo "}" >> $AWKFILE
-
-echo "" >> $AWKFILE
-echo "# reset counters used for variable postfix" >> $AWKFILE
-echo "function resetCounters() {" >> $AWKFILE
 for queryName in $QUERYNAMES
 do
     varName=${queryName}Cnt
     echo "    ${varName}=0" >> $AWKFILE
 done
+
 echo "    # Reset counters for general Solving for extraction" >> $AWKFILE
 echo "    for (varName in subIter)" >> $AWKFILE
 echo "    {" >> $AWKFILE
@@ -302,10 +313,9 @@ echo "}" >> $AWKFILE
 echo "" >> $AWKFILE
 
 
-cat <<LABEL >> $AWKFILE
+cat << AWK_CONTENTS >> $AWKFILE
 # Extract value after columnSel
-function extract(inLine,columnSel,outVar,
-                 a,b)
+function extract(inLine,columnSel,outVar,a,b)
 {
     a=index(inLine, columnSel)
     b=length(columnSel)
@@ -313,90 +323,99 @@ function extract(inLine,columnSel,outVar,
     gsub("[,:]","",outVar[1])
 }
 
-LABEL
+AWK_CONTENTS
+# ----------
 
-
-
-
-
-#-- Generate code for iteration separator (increments 'Iteration')
+#
+# Code for iteration separator (increments 'Iteration')
+#
 getQueries $DBFILE 'Separator'
-cat <<LABSEP >> $AWKFILE
-#-- Iteration separator (increments 'Iteration')
+cat << AWK_CONTENTS >> $AWKFILE
+# Iteration separator (increments 'Iteration')
 /$LINEQ/ {
     Iteration++
     resetCounters()
 }
 
-LABSEP
+AWK_CONTENTS
+# ----------
 
-
-#-- Generate code for extracting Time
+#
+# Code for extracting Time
+#
 getQueries $DBFILE 'Time'
-cat <<LABTIME >> $AWKFILE
-#-- Time extraction (sets 'Time')
+cat << AWK_CONTENTS >> $AWKFILE
+# Time extraction (sets 'Time')
 /$LINEQ/ {
     extract(\$0, "$NUMQ", val)
     Time=val[1]
 }
 
-LABTIME
+AWK_CONTENTS
+# ----------
 
-
-#-- Generate code for singularity handling.
-cat <<LABSING >> $AWKFILE
-#-- Skip whole line with singularity variable
+#
+# Code for singularity handling.
+#
+cat << AWK_CONTENTS >> $AWKFILE
+# Skip whole line with singularity variable
 /solution singularity/ {
     next;
 }
-LABSING
 
+AWK_CONTENTS
+# ----------
 
-#-- Generate code for extracting solved for quantities
-cat <<LABSOLVE >> $AWKFILE
-#-- Extraction of any solved for variable
+#
+# Code for extracting solved for quantities
+#
+cat << AWK_CONTENTS >> $AWKFILE
+# Extraction of any solved for variable
 /Solving for/ {
     extract(\$0, "Solving for ", varNameVal)
 
     varName=varNameVal[1]
     file=varName "_" subIter[varName]++
-    file="$CASEDIR/logs/" file 
+    file="$outputDir/" file
     extract(\$0, "Initial residual = ", val)
-    print $TIMENAME "\t" val[1] > file
+    print $timeName "\t" val[1] > file
 
     varName=varNameVal[1] "FinalRes"
     file=varName "_" subIter[varName]++
-    file="$CASEDIR/logs/" file 
+    file="$outputDir/" file
     extract(\$0, "Final residual = ", val)
-    print $TIMENAME "\t" val[1] > file
+    print $timeName "\t" val[1] > file
 
     varName=varNameVal[1] "Iters"
     file=varName "_" subIter[varName]++
-    file="$CASEDIR/logs/" file 
+    file="$outputDir/" file
     extract(\$0, "No Iterations ", val)
-    print $TIMENAME "\t" val[1] > file
+    print $timeName "\t" val[1] > file
 }
 
-LABSOLVE
+AWK_CONTENTS
+# ----------
 
-#-- generate code to process queries
+#
+# Code to process queries
+#
 for queryName in $QUERYNAMES
 do
     getQueries $DBFILE $queryName
-    if [ "$LINEQ" -a "$NUMQ" ]; then
+    if [ "$LINEQ" -a "$NUMQ" ]
+    then
         counter=${queryName}Cnt
 
-        echo "#-- Extraction of $queryName" >> $AWKFILE
+        echo "# Extraction of $queryName" >> $AWKFILE
         echo "/$LINEQ/ {" >> $AWKFILE
         echo "    extract(\$0, \"$NUMQ\", val)" >> $AWKFILE
-        echo "    file=\"$CASEDIR/logs/${queryName}_\" ${counter}" >> $AWKFILE
-        echo "    print $TIMENAME \"\\t\" val[1] > file" >> $AWKFILE
+        echo "    file=\"$outputDir/${queryName}_\" ${counter}" >> $AWKFILE
+        echo "    print $timeName \"\\t\" val[1] > file" >> $AWKFILE
         echo "    ${counter}++" >> $AWKFILE
         echo "}" >> $AWKFILE
         echo "" >> $AWKFILE
     fi
 done
-
 
 
 #-----------------------------
@@ -414,5 +433,6 @@ done
 #-----------------------------
 myEcho "Generated XY files for:"
 getAllQueries $DBFILE $LOG
+myEcho "End"
 
 #------------------------------------------------------------------------------
diff --git a/bin/foamPackBin b/bin/foamPackBin
--- a/bin/foamPackBin
+++ b/bin/foamPackBin
@@ -1,11 +1,11 @@
 #!/bin/sh
-#---------------------------------*- sh -*-------------------------------------
+#------------------------------------------------------------------------------
 # =========                 |
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     |
-#   \\  /    A nd           | Copyright (C) 1991-2010 OpenCFD Ltd.
+#   \\  /    A nd           | Copyright (C) 2004-2011 OpenCFD Ltd.
 #    \\/     M anipulation  |
-#------------------------------------------------------------------------------
+#-------------------------------------------------------------------------------
 # License
 #     This file is part of OpenFOAM.
 #
@@ -23,66 +23,145 @@
 #     along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.
 #
 # Script
-#     foamPackBin <arch> [outputDir]
+#     foamPackBin [OPTION] <archOptions>
 #
 # Description
-#     Packs and compresses binary version of OpenFOAM for release
+#     Pack and compress binary version of OpenFOAM for release
+#
+# Script
+#     foamPackThirdPartyBin [OPTION] <archOptions>
+#
+# Description
+#     Pack and compress binary version of OpenFOAM ThirdParty for release
 #
 #------------------------------------------------------------------------------
+toolsDir="${0%/*}/tools"  # this script is located in the tools/ parent dir
 
-if [ $# -eq 0 ]
-then
-    echo "Error: architecture type expected, exiting"
-    echo
-    echo "Usage : ${0##*/} <arch> [outputDir]"
-    echo
+case "${0##*/}" in
+*ThirdParty*)
+    # for ThirdParty
+    codeBase="OpenFOAM ThirdParty"
+    packDir=ThirdParty-$WM_PROJECT_VERSION
+    listBinDirs=$toolsDir/foamListThirdPartyBinDirs
+    ;;
+*)
+    # regular
+    codeBase="OpenFOAM"
+    packDir=$WM_PROJECT-$WM_PROJECT_VERSION
+    listBinDirs=$toolsDir/foamListBinDirs
+    ;;
+esac
+
+
+usage() {
+    exec 1>&2
+    while [ "$#" -gt 0 ]; do echo "$1"; shift; done
+cat <<USAGE
+Usage: ${0##*/} [OPTION] <archOptions>
+       ${0##*/} [OPTION] -current
+options:
+  -b, -bzip2            use bzip2 instead of gzip compression
+  -c, -current          use current value of \$WM_OPTIONS
+  -o, -output <dir>     specify alternative output directory
+
+* Pack and compress binary version of $codeBase for release
+
+    The value of 'archOptions' normally corresponds to \$WM_OPTIONS
+    The current value of \$WM_OPTIONS = $WM_OPTIONS
+
+USAGE
     exit 1
-fi
-arch=$1
+}
 
-# base arch (w/o precision, optimization, etc)
-baseArch=$(echo "$arch" | sed -e 's@[DS]P.*$@@')
 
-timeStamp=$(date +%Y-%m-%d)
-packDir=$WM_PROJECT-$WM_PROJECT_VERSION
-packFile=${packDir}.${arch}_${timeStamp}.gtgz
+unset archOptions outputDir
+packExt=tgz
 
-# add optional output directory
-if [ -d "$2" ]
-then
-    packFile="$2/$packFile"
-fi
-
-if [ -f $packFile ]
-then
-    echo "Error: $packFile already exists"
-    exit 1
-fi
-
-# check for essential directories
-for dir in $packDir $packDir/lib/$arch $packDir/applications/bin/$arch
+# parse options
+while [ "$#" -gt 0 ]
 do
-    if [ ! -d $dir ]
-    then
-        echo "Error: directory $dir does not exist"
-        exit 1
-    fi
+    case "$1" in
+    -h | -help)
+        usage
+        ;;
+    -b | -bzip2)
+        packExt=tbz
+        shift
+        ;;
+    -c | -current)      # use $WM_OPTIONS - eg, 'linux64GccDPOpt'
+        archOptions="$WM_OPTIONS"
+        shift
+        ;;
+    -o | -output)
+        [ "$#" -ge 2 ] || usage "'$1' option requires an argument"
+        outputDir=${2%%/}
+        shift 2
+        ;;
+    -*)
+        usage "unknown option: '$*'"
+        ;;
+    *)
+        break
+        ;;
+    esac
 done
 
+if [ -n "$archOptions" ]
+then
+    [ $# -eq 0 ] || usage "Error: cannot specify both -current and architecture"
+else
+    archOptions="$1"
+    [ $# -eq 1 ] || usage "Error: specify architecture"
+fi
+
+
+#------------------------------------------------------------------------------
+timeStamp=$(date +%Y-%m-%d)
+packBase=${packDir}.${archOptions}_${timeStamp}
+
+# add optional output directory
+[ -d "$outputDir" ] && packBase="$outputDir/$packBase"
+packFile=$packBase.$packExt
+
+# avoid overwriting old pack file
+if [ -f $packFile ]
+then
+    echo "Error: $packFile already exists" 1>&2
+    exit 1
+fi
+
+
+#------------------------------------------------------------------------------
+
 # get list of directories
-dirList=`foamBinDirs $packDir $arch`
+dirList=$( $listBinDirs $packDir $archOptions )
+if [ $? -eq 0 -a -n "$dirList" ]
+then
+    echo "Pack into $packFile" 1>&2
+    echo 1>&2
+else
+    exit 1
+fi
 
-echo
-echo "Packing $arch ($baseArch) port of $packDir into $packFile"
-echo
+# bzip2 or gzip compression
+case "$packFile" in
+*tbz)
+    tarOpt=cpjf
+    ;;
+*)
+    tarOpt=cpzf
+    ;;
+esac
 
-tar czpf $packFile $dirList
+# Clean up on Ctrl-C
+trap 'rm -f $packFile 2>/dev/null' INT
 
+tar $tarOpt $packFile $dirList
 if [ $? -eq 0 ]
 then
-    echo "Finished packing and compressing file $packFile"
+    echo "Finished packing file $packFile" 1>&2
 else
-    echo "Error: failure packing $packFile"
+    echo "Error: failure packing $packFile" 1>&2
     rm -f $packFile 2>/dev/null
 fi
 
diff --git a/bin/foamPackBinAll b/bin/foamPackBinAll
--- a/bin/foamPackBinAll
+++ b/bin/foamPackBinAll
@@ -1,11 +1,11 @@
 #!/bin/sh
-#---------------------------------*- sh -*-------------------------------------
+#------------------------------------------------------------------------------
 # =========                 |
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     |
-#   \\  /    A nd           | Copyright (C) 1991-2010 OpenCFD Ltd.
+#   \\  /    A nd           | Copyright (C) 2004-2011 OpenCFD Ltd.
 #    \\/     M anipulation  |
-#------------------------------------------------------------------------------
+#-------------------------------------------------------------------------------
 # License
 #     This file is part of OpenFOAM.
 #
@@ -23,24 +23,64 @@
 #     along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.
 #
 # Script
-#     foamPackBinAll [outputDir]
+#     foamPackBinAll [OPTION]
 #
 # Description
-#     Packs and compresses all binary versions of foam for release
+#     Pack and compress all binary versions of OpenFOAM for release
+#
+# Script
+#     foamPackThirdPartyBinAll [OPTION]
+#
+# Description
+#     Pack and compress all binary versions of OpenFOAM ThirdParty for release
 #
 #------------------------------------------------------------------------------
-packDir=$WM_PROJECT-$WM_PROJECT_VERSION
+binDir="${0%/*}"  # this script is located in the bin/ dir
 
-if [ ! -d $packDir ]
-then
-    echo "Error: directory $packDir does not exist"
+case "${0##*/}" in
+*ThirdParty*)
+    # for ThirdParty
+    packDir=ThirdParty-$WM_PROJECT_VERSION
+    packBin=foamPackThirdPartyBin
+    ;;
+*)
+    # regular
+    packDir=$WM_PROJECT-$WM_PROJECT_VERSION
+    packBin=foamPackBin
+    ;;
+esac
+
+
+[ -d $packDir ] || {
+    echo "Error: directory $packDir does not exist" 1>&2
     exit 1
-fi
+}
 
-# obtain arch types from lib/
-for bin in $packDir/lib/*
-do
-    foamPackBin ${bin##*/} $@
-done
+
+if [ -d $packDir/lib ]
+then
+
+    # obtain archOptions types from lib/<archOptions>
+    for archOptions in $packDir/lib/*
+    do
+        $binDir/$packBin $@ ${archOptions##*/}
+    done
+
+elif [ -d $packDir/platforms ]
+then
+
+    # obtain archOptions types from platforms/<archOptions>/lib
+    for archOptions in $packDir/platforms/*/lib
+    do
+        archOptions=${archOptions%%/lib}
+        $binDir/$packBin $@ ${archOptions##*/}
+    done
+
+else
+
+    echo "Error: directory $packDir does not appear packable" 1>&2
+    exit 1
+
+fi
 
 #------------------------------------------------------------------------------
diff --git a/bin/foamPackDoxygen b/bin/foamPackDoxygen
--- a/bin/foamPackDoxygen
+++ b/bin/foamPackDoxygen
@@ -1,11 +1,11 @@
 #!/bin/sh
-#---------------------------------*- sh -*-------------------------------------
+#------------------------------------------------------------------------------
 # =========                 |
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     |
-#   \\  /    A nd           | Copyright (C) 1991-2010 OpenCFD Ltd.
+#   \\  /    A nd           | Copyright (C) 2008-2011 OpenCFD Ltd.
 #    \\/     M anipulation  |
-#------------------------------------------------------------------------------
+#-------------------------------------------------------------------------------
 # License
 #     This file is part of OpenFOAM.
 #
@@ -26,38 +26,52 @@
 #     foamPackDoxygen [-prefix DIR] [-o outputDir]
 #
 # Description
-#     Packs and compresses the OpenFOAM doxygen html for release
+#     Pack and compress the OpenFOAM doxygen html for release
 #
 #------------------------------------------------------------------------------
 packDir=$WM_PROJECT-$WM_PROJECT_VERSION
-packTag=_Doxygen.gtgz
+htmlDir=doc/Doxygen/html
 
 usage() {
-    while [ $# -gt 0 ]; do echo "$1" 1>&2; shift; done
-cat <<USAGE 1>&2
-Usage: ${0##*/} [-prefix DIR] [-o outputDir]
+    exec 1>&2
+    while [ "$#" -gt 0 ]; do echo "$1"; shift; done
+cat <<USAGE
+Usage: ${0##*/} [OPTION]
+options:
+  -b, -bzip2            use bzip2 instead of gzip compression
+  -o, -output <dir>     specify alternative output directory
+  -prefix <dir>         use alternative prefix
 
-    Packs and compresses the OpenFOAM doxygen html for release
+* Pack and compress the OpenFOAM doxygen html for release
 
 USAGE
     exit 1
 }
 
-unset prefix outputDir
 
+unset prefix outputDir
+packExt=tgz
+
+# parse options
 while [ "$#" -gt 0 ]
 do
     case $1 in
-    -prefix | --prefix )
-        prefix=${2%%/}
-        shift 2
+    -h | -help)
+        usage
         ;;
-    -o | -output )
+    -b | -bzip2)
+        packExt=tbz
+        shift
+        ;;
+    -o | -output)
+        [ "$#" -ge 2 ] || usage "'$1' option requires an argument"
         outputDir=${2%%/}
         shift 2
         ;;
-    -h | -help )
-        usage
+    -prefix | --prefix)
+        [ "$#" -ge 2 ] || usage "'$1' option requires an argument"
+        prefix=${2%%/}
+        shift 2
         ;;
     -*)
         usage "unknown option: '$*'"
@@ -81,41 +95,53 @@ then
     exit 1
 fi
 
-#
+#------------------------------------------------------------------------------
+packName=${packDir}_Doxygen
+
 # add optional output directory
-#
-if [ -d "$outputDir" ]
-then
-    packFile="$outputDir/$packDir$packTag"
-else
-    packFile="$packDir$packTag"
-fi
+[ -d "$outputDir" ] && packName="$outputDir/$packName"
+packFile=$packName.$packExt
 
 
 if [ -f $packFile ]
 then
-    echo "Error: $packFile already exists"
+    echo "Error: $packFile already exists" 1>&2
     exit 1
 fi
 
-# Pack and compress the packFile using GNU tar
-# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-echo
-echo "Packing doxygen html into $packFile"
-echo
+cat <<INFO 1>&2
+-------------------------------------------------------------------------------
+Packing doxygen html into $packFile
+
+INFO
+
+# bzip2 or gzip compression
+case "$packFile" in
+*tbz)
+    tarOpt=cpjf
+    ;;
+*)
+    tarOpt=cpzf
+    ;;
+esac
+
+# Clean up on Ctrl-C
+trap 'rm -f $packFile 2>/dev/null' INT
 
 if [ -n "$prefix" ]
 then
-    tar czpf $packFile --transform="s@^@$prefix/@" doc/Doxygen/html
+    # requires GNU tar
+    tar $tarOpt $packFile --transform="s@^@$prefix/@" $htmlDir
 else
-    tar czpf $packFile $packDir/doc/Doxygen/html
+    tar $tarOpt $packFile $packDir/$htmlDir
 fi
 
 if [ $? -eq 0 ]
 then
-    echo "Finished packing doxygen html into file $packFile"
+    echo "Finished packing doxygen html into $packFile" 1>&2
 else
-    echo "Error: failure packing doxygen html file $packFile"
+    echo "Error: failure packing doxygen html into $packFile" 1>&2
+    rm -f $packFile 2>/dev/null
 fi
 
 #------------------------------------------------------------------------------
diff --git a/bin/foamPrintJobs b/bin/foamPrintJobs
--- a/bin/foamPrintJobs
+++ b/bin/foamPrintJobs
@@ -1,11 +1,11 @@
 #!/bin/sh
-#---------------------------------*- sh -*-------------------------------------
+#------------------------------------------------------------------------------
 # =========                 |
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     |
-#   \\  /    A nd           | Copyright (C) 1991-2010 OpenCFD Ltd.
+#   \\  /    A nd           | Copyright (C) 2004-2010 OpenCFD Ltd.
 #    \\/     M anipulation  |
-#------------------------------------------------------------------------------
+#-------------------------------------------------------------------------------
 # License
 #     This file is part of OpenFOAM.
 #
@@ -29,10 +29,8 @@
 #     Uses finishedJobs/ and runningJobs/ and stateFile to print job info
 #
 #------------------------------------------------------------------------------
+Script=${0##*/}
 
-PROGNAME=`basename $0`
-TMPFILE=/tmp/${PROGNAME}$$.tmp
-TMPFILE2=/tmp/${PROGNAME}$$.tmp2
 JOBSTRING='%4s %8s %20s %10s %8s %4s %12s %12s %20s\n'
 DEFSTATEFILE=$HOME/.OpenFOAM/foamCheckJobs.out
 
@@ -43,18 +41,19 @@ DEFSTATEFILE=$HOME/.OpenFOAM/foamCheckJobs.out
 #
 #-------------------------------------------------------------------------------
 
-printUsage() {
-cat << LABEL
-Usage: $PROGNAME [stateFile]
+usage() {
+    cat<<USAGE
+Usage: $Script [stateFile]
 
-This program prints a table of all the running and finished jobs.
+This program prints a table of all running and finished jobs.
 
 It is normally used in conjunction with foamCheckJobs which outputs
 a "stateFile" containing the actual process status of all jobs.
 
-If stateFile is not supplied the default $DEFSTATEFILE
-is used.
-LABEL
+If stateFile is not supplied, the default is used:
+    $DEFSTATEFILE
+USAGE
+    exit 1
 }
 
 
@@ -80,7 +79,8 @@ getEntry() {
 # notEmpty directory
 # Returns 0 if directory contains files/directories
 notEmpty() {
-    if [ "`ls $1`" ]; then
+    if [ "`ls $1`" ]
+    then
         return 0
     else
         return 1
@@ -103,37 +103,47 @@ leftStr() {
 #
 #-------------------------------------------------------------------------------
 
-if [ ! "$FOAM_JOB_DIR" ]; then
-    echo "$PROGNAME : FOAM_JOB_DIR environment variable not set."
-    exit 1
-fi
-
-if [ ! -d "$FOAM_JOB_DIR" ]; then
-    echo "$PROGNAME : directory does not exist."
-    echo "            FOAM_JOB_DIR: $FOAM_JOB_DIR"
-fi
-if [ ! -d "$FOAM_JOB_DIR/runningJobs" -o ! -d "$FOAM_JOB_DIR/finishedJobs" ]; then
-    echo "$PROGNAME : invalid directory."
-    echo "            FOAM_JOB_DIR: $FOAM_JOB_DIR"
-fi
-
-
-if [ $# -eq 1 ]; then
-    if [ "$1" = '-h' ]; then
-        printUsage
-        exit 1
+if [ $# -eq 1 ]
+then
+    if [ "$1" = "-h" -o "$1" = "-help" ]
+    then
+        usage
     else
-        STATEFILE=$1
+        STATEFILE="$1"
     fi
-elif [ $# -eq 0 ]; then
+elif [ $# -eq 0 ]
+then
     STATEFILE=${STATEFILE:-$DEFSTATEFILE}
 else
-    printUsage
+    usage
+fi
+
+#- Check a few things
+
+if [ ! "$FOAM_JOB_DIR" ]
+then
+    echo "$Script : FOAM_JOB_DIR environment variable not set."
+    echo
+    exit 1
+fi
+if [ ! -d "$FOAM_JOB_DIR" ]
+then
+    echo "$Script : directory does not exist."
+    echo "    FOAM_JOB_DIR=$FOAM_JOB_DIR"
+    echo
+    exit 1
+fi
+if [ ! -d "$FOAM_JOB_DIR/runningJobs" -o ! -d "$FOAM_JOB_DIR/finishedJobs" ]
+then
+    echo "$Script : invalid directory."
+    echo "    FOAM_JOB_DIR=$FOAM_JOB_DIR"
+    echo
     exit 1
 fi
 
 
-if [ -f "$STATEFILE" ]; then
+if [ -f "$STATEFILE" ]
+then
     echo ""
     echo "Using process information from"
     echo "  $STATEFILE"
@@ -159,7 +169,8 @@ printJob '----' '----' '----' '-------' '---' '----' '-----' '---' '----'
 
 #-- print running
 echo "Running:"
-if notEmpty $FOAM_JOB_DIR/runningJobs; then
+if notEmpty $FOAM_JOB_DIR/runningJobs
+then
     for f in `ls -t $FOAM_JOB_DIR/runningJobs/*`
     do
         machinePid=`basename $f`
@@ -169,14 +180,15 @@ if notEmpty $FOAM_JOB_DIR/runningJobs; then
 
         pid=`echo $machinePid | sed -e 's/.*\.\([0-9][0-9]*\)$/\1/'`
 
-        if [ "$STATEFILE" ]; then
+        if [ "$STATEFILE" ]
+        then
             stat=`getEntry $STATEFILE $machinePid`
         fi
         stat=${stat:-'UNKN'}
 
         case=`getEntry $f 'case'`
         case=${case:-'---'}
-        case=`echo $case | sed -e 's!/.*!!'`       #strip of processorXXX ending
+        case=`echo $case | sed -e 's!/.*!!'`  # strip processorXXX ending
         case=`rightStr 20 "$case"`
 
         start=`getEntry $f 'startDate'`
@@ -186,7 +198,8 @@ if notEmpty $FOAM_JOB_DIR/runningJobs; then
         end='---'
 
         code=`getEntry $f 'code'`
-        if [ "$code" ]; then
+        if [ "$code" ]
+        then
             code=`basename $code`
         else
             code='---'
@@ -195,7 +208,8 @@ if notEmpty $FOAM_JOB_DIR/runningJobs; then
 
         nProcs=`getEntry $f 'nProcs'`
         nProcs=${nProcs:-'1'}
-        if [ $nProcs -eq 1 ]; then
+        if [ $nProcs -eq 1 ]
+        then
             nProcs='---'
         fi
         nProcs=`rightStr 3 "$nProcs"`
@@ -212,7 +226,8 @@ fi
 #-- print finished
 echo ""
 echo "Finished:"
-if notEmpty $FOAM_JOB_DIR/finishedJobs; then
+if notEmpty $FOAM_JOB_DIR/finishedJobs
+then
     for f in `ls -t $FOAM_JOB_DIR/finishedJobs/*`
     do
         machinePid=`basename $f`
@@ -226,13 +241,14 @@ if notEmpty $FOAM_JOB_DIR/finishedJobs; then
         end=${end:-'---'}
         end=`leftStr 12 "$end"`
 
-        if [ "$STATEFILE" ]; then
+        if [ "$STATEFILE" ]
+        then
             stat=`getEntry $STATEFILE $machinePid`
         fi
         stat=${stat:-'UNKN'}
 
         case=`getEntry $f case`
-        case=`echo $case | sed -e 's!/.*!!'`       #strip of processorXXX ending
+        case=`echo $case | sed -e 's!/.*!!'`  # strip processorXXX ending
         case=${case:-'---'}
         case=`rightStr 20 "$case"`
 
@@ -241,7 +257,8 @@ if notEmpty $FOAM_JOB_DIR/finishedJobs; then
         start=`leftStr 12 "$start"`
 
         code=`getEntry $f code`
-        if [ "$code" ]; then
+        if [ "$code" ]
+        then
             code=`basename $code`
         else
             code='---'
@@ -250,7 +267,8 @@ if notEmpty $FOAM_JOB_DIR/finishedJobs; then
 
         nProcs=`getEntry $f 'nProcs'`
         nProcs=${nProcs:-'1'}
-        if [ $nProcs -eq 1 ]; then
+        if [ $nProcs -eq 1 ]
+        then
             nProcs='---'
         fi
         nProcs=`rightStr 3 "$nProcs"`
diff --git a/bin/foamTags b/bin/foamTags
--- a/bin/foamTags
+++ b/bin/foamTags
@@ -1,11 +1,11 @@
 #!/bin/sh
-#---------------------------------*- sh -*-------------------------------------
+#------------------------------------------------------------------------------
 # =========                 |
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     |
-#   \\  /    A nd           | Copyright (C) 1991-2010 OpenCFD Ltd.
+#   \\  /    A nd           | Copyright (C) 2004-2010 OpenCFD Ltd.
 #    \\/     M anipulation  |
-#------------------------------------------------------------------------------
+#-------------------------------------------------------------------------------
 # License
 #     This file is part of OpenFOAM.
 #
@@ -30,16 +30,28 @@
 #
 #------------------------------------------------------------------------------
 
-if [ $# -ne 0 ]; then
-   echo "Usage : ${0##*/}"
-   echo ""
-   echo "Build the tags files for all the .C and .H files"
-   echo ""
-   exit 1
+if [ $# -ne 0 ]
+then
+    echo "Usage : ${0##*/}"
+    echo ""
+    echo "Build the tags files for all the .C and .H files"
+    echo ""
+    exit 1
 fi
 
-cd $WM_PROJECT_DIR
+
+for cmd in etags ectags
+do
+    type $cmd >/dev/null 2>&1 || {
+        echo "${0##*/} cannot build tag files: '$cmd' command not found"
+        exit 1
+    }
+done
+
+
+cd $WM_PROJECT_DIR || exit 1
 mkdir .tags 2>/dev/null
+
 
 etagsCmd="etags --declarations -l c++ -o .tags/etags -"
 #etagsDefCmd="etags -l c++ -o .tags/etagsDef -"
diff --git a/bin/tools/CleanFunctions b/bin/tools/CleanFunctions
--- a/bin/tools/CleanFunctions
+++ b/bin/tools/CleanFunctions
@@ -2,7 +2,7 @@
 # =========                 |
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     |
-#   \\  /    A nd           | Copyright (C) 1991-2009 OpenCFD Ltd.
+#   \\  /    A nd           | Copyright (C) 2008-2011 OpenCFD Ltd.
 #    \\/     M anipulation  |
 #------------------------------------------------------------------------------
 # License
@@ -25,44 +25,85 @@
 #     CleanFunctions
 #
 # Description
-#
+#     Miscellaneous cleanup functions for tutorial cases
 #------------------------------------------------------------------------------
 
-cleanTimeDirectories ()
+#cleanTimeDirectories()
+#{
+#    echo "Cleaning $PWD case"
+#    for time in $(foamInfoExec -times)
+#    do
+#        # keep 0 and constant directories
+#        [ "$time" = "0" -o "$time" = constant ] || {
+#            echo "Deleting directory $time"
+#            rm -rf $time > /dev/null 2>&1
+#        }
+#    done
+#    rm -rf {log,log.*,log-*,logSummary.*,.fxLock,*.xml,ParaView*,paraFoam*,*.OpenFOAM} > /dev/null 2>&1
+#}
+
+cleanTimeDirectories()
 {
     echo "Cleaning $PWD case"
-    nZeros=0
     zeros=""
-    while [ $nZeros -lt 8 ] ; do
+    while [ ${#zeros} -lt 8 ]
+    do
         timeDir="0.${zeros}[1-9]*"
-        rm -rf ${timeDir} > /dev/null 2>&1
-        rm -rf ./-${timeDir} > /dev/null 2>&1
-        zeros=`printf %0${nZeros}d 0`
-        nZeros=$(($nZeros + 1))
+        rm -rf ./${timeDir} ./-${timeDir} > /dev/null 2>&1
+        zeros="0$zeros"
     done
-    rm -rf [1-9]* ./-[1-9]* log log.* log-* logSummary.* *.xml ParaView* paraFoam* *.OpenFOAM > /dev/null 2>&1
+    rm -rf ./[1-9]* ./-[1-9]* ./log ./log.* ./log-* ./logSummary.* ./.fxLock ./*.xml ./ParaView* ./paraFoam* ./*.OpenFOAM ./.setSet > /dev/null 2>&1
 }
 
-cleanCase ()
+
+#
+# Remove dynamicCode subdirectory if it looks appropriate
+#
+cleanDynamicCode()
+{
+    if [ -d system -a -d dynamicCode ]
+    then
+        rm -rf dynamicCode > /dev/null 2>&1
+    fi
+}
+
+
+cleanCase()
 {
     cleanTimeDirectories
+    cleanDynamicCode
+
     rm -rf processor* > /dev/null 2>&1
     rm -rf probes* > /dev/null 2>&1
     rm -rf forces* > /dev/null 2>&1
+    rm -rf graphs* > /dev/null 2>&1
+    rm -rf sets > /dev/null 2>&1
+    rm -rf surfaceSampling > /dev/null 2>&1
+    rm -rf cuttingPlane > /dev/null 2>&1
     rm -rf system/machines > /dev/null 2>&1
-    (cd constant/polyMesh && \
-        rm -rf \
-        allOwner* cell* face* meshModifiers* \
-        owner* neighbour* point* edge* \
-        cellLevel* pointLevel* refinementHistory* surfaceIndex* sets \
-        > /dev/null 2>&1 \
-    )
+
+    if [ -d constant/polyMesh ]
+    then
+        (cd constant/polyMesh && \
+            rm -rf \
+            allOwner* cell* face* meshModifiers* \
+            owner* neighbour* point* edge* \
+            cellLevel* pointLevel* refinementHistory* surfaceIndex* sets \
+            > /dev/null 2>&1 \
+        )
+    fi
     (cd constant && \
         rm -rf \
         cellToRegion cellLevel* pointLevel* \
         > /dev/null 2>&1 \
     )
     rm -rf VTK > /dev/null 2>&1
+    rm -f 0/cellLevel 0/pointLevel
+
+    if [ -e constant/polyMesh/blockMeshDict.m4 ]
+    then
+        rm -f constant/polyMesh/blockMeshDict > /dev/null 2>&1
+    fi
 
     for f in `find . -name "*Dict"`
     do
@@ -71,23 +112,23 @@ cleanCase ()
     done
 }
 
-removeCase ()
+removeCase()
 {
-    echo "Removing $case case"
+    echo "Removing ${1:-unknown} case"
     rm -rf $1
 }
 
-cleanSamples ()
+cleanSamples()
 {
-    rm -rf sets samples sampleSurfaces > /dev/null 2>&1
+    rm -rf ./sets ./samples ./sampleSurfaces > /dev/null 2>&1
 }
 
-cleanUcomponents ()
+cleanUcomponents()
 {
     rm -rf 0/Ux 0/Uy 0/Uz > /dev/null 2>&1
 }
 
-cleanApplication ()
+cleanApplication()
 {
     echo "Cleaning $PWD application"
     wclean
diff --git a/src/Allwmake b/src/Allwmake
--- a/src/Allwmake
+++ b/src/Allwmake
@@ -1,63 +1,74 @@
 #!/bin/sh
 cd ${0%/*} || exit 1    # run from this directory
+makeType=${1:-libso}
 
-if [ "$PWD" != "$WM_PROJECT_DIR/src" ]
-then
-    echo "Error: Current directory in not \$WM_PROJECT_DIR/src"
-    echo "    The environment variable are not consistent with the installation."
+wmakeCheckPwd "$WM_PROJECT_DIR/src" || {
+    echo "Error: Current directory is not \$WM_PROJECT_DIR/src"
+    echo "    The environment variables are inconsistent with the installation."
     echo "    Check the OpenFOAM entries in your dot-files and source them."
     exit 1
-fi
+}
+
+[ -n "$FOAM_EXT_LIBBIN" ] || {
+    echo "Error: FOAM_EXT_LIBBIN not set"
+    echo "    Check the OpenFOAM entries in your dot-files and source them."
+    exit 1
+}
 
 set -x
 
 # update OpenFOAM version strings if required
-wmakePrintBuild -check || /bin/rm -f OpenFOAM/Make/$WM_OPTIONS/global.? 2>/dev/null
+wmakePrintBuild -check || /bin/rm -f OpenFOAM/Make/*/global.? 2>/dev/null
 
 wmakeLnInclude OpenFOAM
-wmakeLnInclude OSspecific/$WM_OSTYPE
-Pstream/Allwmake
+wmakeLnInclude OSspecific/${WM_OSTYPE:-POSIX}
+Pstream/Allwmake $*
 
-wmake libo  OSspecific/$WM_OSTYPE
-wmake libso OpenFOAM
+OSspecific/${WM_OSTYPE:-POSIX}/Allwmake
+wmake $makeType OpenFOAM
 
-wmake libso lagrangian/basic
+wmake $makeType fileFormats
+wmake $makeType triSurface
+wmake $makeType meshTools
+wmake $makeType edgeMesh
+wmake $makeType surfMesh
 
-wmake libso triSurface
-wmake libso edgeMesh
-wmake libso surfMesh
+# Decomposition methods needed by dummyThirdParty
+parallel/decompose/AllwmakeLnInclude
+# dummyThirdParty (dummy metisDecomp, scotchDecomp etc) needed by e.g. meshTools
+dummyThirdParty/Allwmake $*
 
-# Decomposition methods needed by meshTools
-decompositionMethods/AllwmakeLnInclude
-dummyThirdParty/Allwmake
-decompositionMethods/Allwmake
+wmake $makeType finiteVolume
+wmake $makeType lagrangian/basic
+wmake $makeType lagrangian/distributionModels
+wmake $makeType genericPatchFields
 
-wmake libso meshTools
-wmake libso finiteVolume
-wmake libso genericPatchFields
+# Build the proper scotchDecomp, metisDecomp etc.
+parallel/Allwmake $*
 
-wmake libso sampling
+wmake $makeType conversion
 
-wmake libso dynamicMesh
-wmake libso dynamicFvMesh
-wmake libso topoChangerFvMesh
+wmake $makeType sampling
 
-wmake libso ODE
-wmake libso randomProcesses
+wmake $makeType dynamicMesh
+wmake $makeType dynamicFvMesh
+wmake $makeType topoChangerFvMesh
 
-thermophysicalModels/Allwmake
-transportModels/Allwmake
-turbulenceModels/Allwmake
-lagrangian/Allwmake
-postProcessing/Allwmake
-conversion/Allwmake
+wmake $makeType ODE
+wmake $makeType randomProcesses
 
-wmake libso autoMesh
-wmake libso errorEstimation
+thermophysicalModels/Allwmake $*
+transportModels/Allwmake $*
+turbulenceModels/Allwmake $*
+wmake $makeType combustionModels
+regionModels/Allwmake $*
+lagrangian/Allwmake $*
+postProcessing/Allwmake $*
+mesh/Allwmake $*
 
-fvAgglomerationMethods/Allwmake
+fvAgglomerationMethods/Allwmake $*
 
-wmake libso fvMotionSolver
-wmake libso engine
+wmake $makeType fvMotionSolver
+wmake $makeType engine
 
 # ----------------------------------------------------------------- end-of-file
diff --git a/wmake/scripts/makeOptions b/wmake/scripts/makeOptions
--- a/wmake/scripts/makeOptions
+++ b/wmake/scripts/makeOptions
@@ -1,9 +1,9 @@
 #!/bin/sh
-#---------------------------------*- sh -*-------------------------------------
+#------------------------------------------------------------------------------
 # =========                 |
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     |
-#   \\  /    A nd           | Copyright (C) 1991-2010 OpenCFD Ltd.
+#   \\  /    A nd           | Copyright (C) 2004-2010 OpenCFD Ltd.
 #    \\/     M anipulation  |
 #------------------------------------------------------------------------------
 # License
@@ -26,7 +26,7 @@
 #     makeOptions
 #
 # Description
-#     Scan the current directory for options and construct Make/options
+#     Construct Make/options
 #
 #     Usage : makeOptions
 #
@@ -34,8 +34,8 @@
 
 if [ -r Make/options ]
 then
-   echo "makeOptions: Make/options already exists, exiting"
-   exit 1
+    echo "Error: Make/options already exists - exiting"
+    exit 1
 fi
 
 [ -d Make ] || mkdir Make
diff --git a/wmake/wclean b/wmake/wclean
--- a/wmake/wclean
+++ b/wmake/wclean
@@ -1,11 +1,11 @@
 #!/bin/sh
-#---------------------------------*- sh -*-------------------------------------
+#------------------------------------------------------------------------------
 # =========                 |
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     |
-#   \\  /    A nd           | Copyright (C) 1991-2010 OpenCFD Ltd.
+#   \\  /    A nd           | Copyright (C) 2004-2011 OpenCFD Ltd.
 #    \\/     M anipulation  |
-#------------------------------------------------------------------------------
+#-------------------------------------------------------------------------------
 # License
 #     This file is part of OpenFOAM.
 #
@@ -26,8 +26,8 @@
 #     wclean
 #
 # Description
-#     Clean up the wmake control directory Make and remove the include
-#     directories generated for libraries.
+#     Clean up the wmake control directory Make/\$WM_OPTIONS and remove the
+#     lnInclude directories generated for libraries.
 #
 #------------------------------------------------------------------------------
 Script=${0##*/}
@@ -35,35 +35,53 @@ Script=${0##*/}
 usage() {
     while [ "$#" -ge 1 ]; do echo "$1"; shift; done
     cat<<USAGE
-usage: $Script [dir]
-       $Script target [dir [MakeDir]]
 
-Clean up the wmake control directory Make and remove the include
-directories generated for libraries.
+Usage: $Script [OPTION] [dir]
+       $Script [OPTION] target [dir [MakeDir]]
+
+options:
+  -s | -silent      ignored - for compatibility with wmake
+  -help             print the usage
+
+Clean up the wmake control directory Make/\$WM_OPTIONS and remove the
+lnInclude directories generated for libraries.
 
 The targets correspond to a subset of the 'wmake' special targets:
-    all       all subdirectories
-    exe       cleans dir/Make
-    lib       cleans dir/Make and dir/lnInclude
-    libso     cleans dir/Make and dir/lnInclude
-    libo      cleans dir/Make and dir/lnInclude
+  all               all subdirectories, uses any Allwclean or Allclean
+                    files if they exist
+  exe | lib | libo | libso
+                    clean Make, any *.dep files and lnInclude directories
 
 USAGE
-   exit 1
+    exit 1
 }
 
-# provide immediate help
-if [ "$1" = "-h" -o "$1" = "-help" ]
-then
-    usage
-fi
+
+# parse options
+while [ "$#" -gt 0 ]
+do
+    case "$1" in
+    -h | -help)
+        usage
+        ;;
+    -s | -silent)    # ignored - for compatibility with wmake
+        shift
+        ;;
+    -*)
+        usage "unknown option: '$*'"
+        ;;
+    *)
+        break
+        ;;
+    esac
+done
 
 
 #------------------------------------------------------------------------------
-# check arguments and change to the directory in which to run wmake
+# check arguments and change to the directory in which to run wclean
 #------------------------------------------------------------------------------
 
-unset dir makeOption
+unset dir makeType
 MakeDir=Make
 
 if [ $# -ge 1 ]
@@ -73,19 +91,14 @@ then
     then
         dir=$1
     else
-        makeOption=$1
+        makeType=$1
     fi
 
-    if [ $# -ge 2 ]
-    then
-        dir=$2
-    fi
+    # specified directory name:
+    [ $# -ge 2 ] && dir=$2
 
-    # alternative name for the Make sub-directory
-    if [ $# -ge 3 ]
-    then
-        MakeDir=$3
-    fi
+    # specified alternative name for the Make sub-directory:
+    [ $# -ge 3 ] && MakeDir=$3
 
     if [ "$dir" ]
     then
@@ -103,35 +116,39 @@ fi
 # Recurse the directories tree
 #------------------------------------------------------------------------------
 
-if [ "$makeOption" = all ]
+if [ "$makeType" = all ]
 then
-    if [ -e Allclean ]
+    if [ -e Allwclean ]       # consistent with Allwmake
+    then
+        ./Allwclean
+        exit $?
+    elif [ -e Allclean ]      # often used for tutorial cases
     then
         ./Allclean
         exit $?
     elif [ ! -d $MakeDir ]
     then
-        for dir in `find . \( -type d -a -name Make \) -printf "%h "`
+        for dir in `find . \( -type d -a -name Make \)`
         do
-            $0 $dir
+            $0 ${dir%/Make}   # parent directory - trim /Make from the end
         done
         exit 0
     fi
-
-    # This is the end of the recursion down the application directories tree
-    # so remove the "all" option so that the call to make builds the application
-    makeOption=
 fi
 
+# makeType is not needed beyond this point
+unset makeType
+
+
 #------------------------------------------------------------------------------
-# Check the existance of the Make directory
+# Require the existence of the 'Make' directory
 #------------------------------------------------------------------------------
 
-if [ ! -d $MakeDir ]
-then
+[ -d $MakeDir ] || {
     echo "$Script error: '$MakeDir' directory does not exist" 1>&2
     exit 1
-fi
+}
+
 
 # -----------------------------------------------------------------------------
 
@@ -139,13 +156,10 @@ rm -rf $MakeDir/$WM_OPTIONS $MakeDir/classes 2>/dev/null
 
 find . -name "*.dep" -exec rm {} \;
 
-case "$makeOption" in
-lib | libso | libo )
-    rm -rf lnInclude 2>/dev/null
-    ;;
-esac
+# always safe to remove lnInclude
+rm -rf lnInclude 2>/dev/null
 
 rm -rf ii_files Templates.DB 2>/dev/null
-rm -f so_locations
+rm -f so_locations 2>/dev/null
 
 #------------------------------------------------------------------------------
diff --git a/wmake/wmake b/wmake/wmake
--- a/wmake/wmake
+++ b/wmake/wmake
@@ -1,11 +1,11 @@
 #!/bin/sh
-#---------------------------------*- sh -*-------------------------------------
+#------------------------------------------------------------------------------
 # =========                 |
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     |
-#   \\  /    A nd           | Copyright (C) 1991-2010 OpenCFD Ltd.
+#   \\  /    A nd           | Copyright (C) 2004-2011 OpenCFD Ltd.
 #    \\/     M anipulation  |
-#------------------------------------------------------------------------------
+#-------------------------------------------------------------------------------
 # License
 #     This file is part of OpenFOAM.
 #
@@ -32,34 +32,57 @@
 Script=${0##*/}
 
 usage() {
+    exec 1>&2
     while [ "$#" -ge 1 ]; do echo "$1"; shift; done
     cat<<USAGE
-usage: $Script [dir]
-       $Script target [dir [MakeDir]]
+
+Usage: $Script [OPTION] [dir]
+       $Script [OPTION] target [dir [MakeDir]]
+
+options:
+  -s | -silent      invoke make in 'silent' mode (do not echo commands)
+  -help             print the usage
+
 
 A general, easy-to-use make system for multi-platform development
 
 The 'target' is a Makefile target:
-    e.g., Make/linux64GccDPOpt/fvMesh.o
+  e.g., Make/linux64GccDPOpt/fvMesh.o
 
-  or a special target:
-    all       all subdirectories
-    exe       build statically linked executable
-    lib       build statically linked archive lib (.a)
-    libso     build dynamically linked lib (.so)
-    libo      build statically linked lib (.o)
-    jar       build Java jar
+or a special target:
+  all               all subdirectories, uses any Allwmake files if they exist
+  exe               build statically linked executable
+  lib               build statically linked archive lib (.a)
+  libo              build statically linked lib (.o)
+  libso             build dynamically linked lib (.so)
+  jar               build Java jar
 
 USAGE
     exit 1
 }
 
-# provide immediate help, even if none of the environment is set
-if [ "$1" = "-h" -o "$1" = "-help" ]
-then
-    usage
-fi
+# normally use "make"
+make="make"
 
+# parse options
+while [ "$#" -gt 0 ]
+do
+    case "$1" in
+    -h | -help)
+        usage
+        ;;
+    -s | -silent)
+        make="$make -s"
+        shift
+        ;;
+    -*)
+        usage "unknown option: '$*'"
+        ;;
+    *)
+        break
+        ;;
+    esac
+done
 
 #
 # check environment variables
@@ -71,6 +94,7 @@ do
         exit 1
     }
 done
+
 
 # when compiling anything but a standalone exe:
 # WM_PROJECT and WM_PROJECT_DIR must be set
@@ -86,8 +110,6 @@ done
 # Select the version of make to be used
 #------------------------------------------------------------------------------
 
-make="make"
-
 # set WM_NCOMPPROCS automatically when both WM_HOSTS and WM_SCHEDULER are set
 if [ -z "$WM_NCOMPPROCS" -a -n "$WM_HOSTS" -a -n "$WM_SCHEDULER" ]
 then
@@ -99,7 +121,7 @@ if [ "$WM_NCOMPPROCS" ]
 then
     if [ "$WM_NCOMPPROCS" -gt 1 -a ! "$MAKEFLAGS" ]
     then
-        lockDir=$HOME/.wmakeScheduler
+        lockDir=$HOME/.$WM_PROJECT/.wmake
 
         if [ -d $lockDir ]
         then
@@ -108,7 +130,7 @@ then
             mkdir -p $lockDir
         fi
 
-        make="make --no-print-directory -j "$WM_NCOMPPROCS
+        make="$make --no-print-directory -j "$WM_NCOMPPROCS
     fi
 fi
 
@@ -117,7 +139,7 @@ fi
 # check arguments and change to the directory in which to run wmake
 #------------------------------------------------------------------------------
 
-unset dir makeOption
+unset dir makeType
 MakeDir=Make
 
 if [ $# -ge 1 ]
@@ -126,19 +148,14 @@ then
     then
         dir=$1
     else
-        makeOption=$1
+        makeType=$1
     fi
 
-    if [ $# -ge 2 ]
-    then
-        dir=$2
-    fi
+    # specified directory name:
+    [ $# -ge 2 ] && dir=$2
 
-    # alternative name for the Make sub-directory
-    if [ $# -ge 3 ]
-    then
-        MakeDir=$3
-    fi
+    # specified alternative name for the Make sub-directory:
+    [ $# -ge 3 ] && MakeDir=$3
 
     if [ "$dir" ]
     then
@@ -154,7 +171,7 @@ fi
 # Recurse the application directories tree
 #------------------------------------------------------------------------------
 
-if [ "$makeOption" = all ]
+if [ "$makeType" = all ]
 then
     if [ -e Allwmake ]
     then
@@ -168,27 +185,34 @@ then
         $make -k -f $WM_DIR/MakefileApps FOAM_APPS="$FOAM_APPS"
         exit $?
     fi
-
-    # This is the end of the recursion down the application directories tree
-    # so remove the "all" option so that the call to make builds the application
-    makeOption=
 fi
 
 
 #------------------------------------------------------------------------------
-# Check the existance of the Make directory and files file
-# If both exist, make the wmake derived files
+# Require the existence of the 'Make' directory and 'files' file
 #------------------------------------------------------------------------------
 
 [ -d $MakeDir ] || {
-    echo "$Script error: '$MakeDir' directory does not exist" 1>&2
+    echo "$Script error: '$MakeDir' directory does not exist in $PWD" 1>&2
     exit 1
 }
 
 [ -r $MakeDir/files ] || {
-    echo "$Script error: file '$MakeDir/files' does not exist" 1>&2
+    echo "$Script error: file '$MakeDir/files' does not exist in $PWD" 1>&2
     exit 1
 }
+
+# transform "all" option to "libso" if that looks appropriate or remove it
+# so that the call to make builds the application
+if [ "$makeType" = all ]
+then
+    unset makeType
+    if grep -e '^ *LIB *=' "$MakeDir/files" >/dev/null 2>&1
+    then
+        makeType=libso
+    fi
+fi
+
 
 # Spawn a sub-shell and unset MAKEFLAGS in that sub-shell to avoid
 # files and options being built in parallel
@@ -208,7 +232,7 @@ fi
 OBJECTS_DIR=$MakeDir/$WM_OPTIONS
 
 [ -r $OBJECTS_DIR/objectFiles ] || {
-    echo "$Script error: file '$OBJECTS_DIR/objectFiles' could not be created" 1>&2
+    echo "$Script error: file '$OBJECTS_DIR/objectFiles' could not be created in $PWD" 1>&2
     exit 1
 }
 
@@ -219,26 +243,22 @@ OBJECTS_DIR=$MakeDir/$WM_OPTIONS
 
 touch $OBJECTS_DIR/dontIncludeDeps
 
-case "$makeOption" in
-lib | libso | libo )
+case "$makeType" in
+lib | libo | libso )
     $make -s -f $WM_DIR/Makefile MAKE_DIR=$MakeDir INCLUDE_DEPS=$OBJECTS_DIR/dontIncludeDeps lnInclude/uptodate
     ;;
 esac
 
 $make -s -f $WM_DIR/Makefile MAKE_DIR=$MakeDir INCLUDE_DEPS=$OBJECTS_DIR/dontIncludeDeps $OBJECTS_DIR/dependencies
 
-retVal=$?
-if [ $retVal -ne 0 ]
-then
-    exit $retVal
-fi
-
+rc=$?
+[ $rc -eq 0 ] || exit $rc
 
 #------------------------------------------------------------------------------
 # make the object files and link
 #------------------------------------------------------------------------------
 
-cmd="$make -f $WM_DIR/Makefile MAKE_DIR=$MakeDir INCLUDE_DEPS=$OBJECTS_DIR/includeDeps $makeOption"
+cmd="$make -f $WM_DIR/Makefile MAKE_DIR=$MakeDir INCLUDE_DEPS=$OBJECTS_DIR/includeDeps $makeType"
 # echo "cmd=$cmd"
 exec $cmd
 
diff --git a/wmake/wmakeLnInclude b/wmake/wmakeLnInclude
--- a/wmake/wmakeLnInclude
+++ b/wmake/wmakeLnInclude
@@ -1,11 +1,11 @@
 #!/bin/sh
-#---------------------------------*- sh -*-------------------------------------
+#------------------------------------------------------------------------------
 # =========                 |
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     |
-#   \\  /    A nd           | Copyright (C) 1991-2010 OpenCFD Ltd.
+#   \\  /    A nd           | Copyright (C) 2004-2011 OpenCFD Ltd.
 #    \\/     M anipulation  |
-#------------------------------------------------------------------------------
+#-------------------------------------------------------------------------------
 # License
 #     This file is part of OpenFOAM.
 #
@@ -28,7 +28,7 @@
 # Description
 #     Link all the source files in the <dir> directory into <dir>/lnInclude
 #
-#     Usage: wmakeLnInclude [-f] <dir> [-lnOption]
+#     Usage: wmakeLnInclude [-f] <dir>
 #
 #     The desired source files:
 #         *.C *.H *.h *.cpp *.cxx *.hpp *.hxx
@@ -40,16 +40,22 @@
 Script=${0##*/}
 
 usage() {
+    exec 1>&2
     while [ "$#" -ge 1 ]; do echo "$1"; shift; done
     cat<<USAGE
 
-usage: $Script [-f] <dir> [-lnOption]
+Usage: $Script [OPTION] dir
+
+options:
+  -f | -force       force update
+  -s | -silent      use 'silent' mode (do not echo command)
+  -help             print the usage
 
     Link all the source files in the <dir> into <dir>/lnInclude
 
 Note
     The '-f' option forces an update when the lnInclude directory already exists
-    and also changes the default linking from 'ln -s' to 'ln -sf'.
+    and changes the default linking from 'ln -s' to 'ln -sf'.
 
 USAGE
     exit 1
@@ -57,12 +63,13 @@ USAGE
 
 #------------------------------------------------------------------------------
 
-# simple option parsing
-unset forceUpdate
+# default 'find' option
 unset findOpt
 
-# default ln option
+# default 'ln' option
 lnOpt="-s"
+
+unset forceUpdate silentOpt
 
 # simple parse options
 while [ "$#" -gt 0 ]
@@ -71,10 +78,14 @@ do
     -h | -help)   # provide immediate help
         usage
         ;;
-    -f)
-        shift
-        forceUpdate=1
+    -f | -force)
+        forceUpdate=true
         lnOpt="-sf"
+        shift
+        ;;
+    -s | -silent)
+        silentOpt=true
+        shift
         ;;
     -*)
         usage "unknown option: '$*'"
@@ -88,10 +99,6 @@ done
 if [ $# -eq 1 ]
 then
     baseDir=$1
-elif [ $# -eq 2 ]
-then
-    baseDir=$1
-    lnOpt="$2"
 else
     usage "ERROR: incorrect number of arguments"
 fi
@@ -109,35 +116,34 @@ done
 incDir=$baseDir/lnInclude
 
 
-if [ ! -d $baseDir ]
-then
+[ -d $baseDir ] || {
     echo "$Script error: base directory $baseDir does not exist" 1>&2
     exit 2
-fi
+}
 
 if [ -d $incDir ]
 then
-    if [ ! "$forceUpdate" ]
-    then
-       # echo "$Script error: include directory $incDir already exists" 1>&2
-       exit 0
-    fi
+    [ "$forceUpdate" = true ] || {
+        # echo "$Script error: include directory $incDir already exists" 1>&2
+        exit 0
+    }
 else
     mkdir $incDir
 fi
 
-if [ ! -d $incDir ]
-then
+[ -d $incDir ] || {
     echo "$Script error: failed to create include directory $incDir" 1>&2
     exit 0
-fi
+}
 
 cd $incDir || exit 1
 
+#------------------------------------------------------------------------------
 
-# Link include files
-# ~~~~~~~~~~~~~~~~~~
-echo "$Script: linking include files to $incDir"
+if [ "$silentOpt" != true ]
+then
+    echo "$Script: linking include files to $incDir" 1>&2
+fi
 
 #
 # remove any broken links first (this helps when file locations have moved)
