Initial commit for version 2.3.x

diff --git a/wmake/wmake b/wmake/wmake
--- a/wmake/wmake
+++ b/wmake/wmake
@@ -56,6 +56,7 @@ or a special target:
   libo              build statically linked lib (.o)
   libso             build dynamically linked lib (.so)
   jar               build Java jar
+  dep               build lnInclude and dependencies only
 
 USAGE
     exit 1
@@ -84,9 +85,11 @@ do
     esac
 done
 
-#
-# check environment variables
-#
+
+#------------------------------------------------------------------------------
+# Check environment variables
+#------------------------------------------------------------------------------
+
 for check in WM_OPTIONS WM_LINK_LANGUAGE WM_DIR
 do
     eval test "\$$check" || {
@@ -101,13 +104,13 @@ done
 [ "$1" = exe -o \( "$WM_PROJECT" -a "$WM_PROJECT_DIR" \) ] || {
     echo "$Script error:" 1>&2
     echo "    environment variable \$WM_PROJECT or \$WM_PROJECT_DIR not set" 1>&2
-    echo  "   while building project library" 1>&2
+    echo "    while building project library" 1>&2
     exit 1
 }
 
 
 #------------------------------------------------------------------------------
-# Select the version of make to be used
+# Select the version of make use
 #------------------------------------------------------------------------------
 
 # set WM_NCOMPPROCS automatically when both WM_HOSTS and WM_SCHEDULER are set
@@ -136,7 +139,7 @@ fi
 
 
 #------------------------------------------------------------------------------
-# check arguments and change to the directory in which to run wmake
+# Check arguments and change to the directory in which to run wmake
 #------------------------------------------------------------------------------
 
 unset dir makeType
@@ -189,18 +192,64 @@ fi
 
 
 #------------------------------------------------------------------------------
-# Require the existence of the 'Make' directory and 'files' file
+# Search up directories tree for the Make sub-directory and build there
+# Also check the existance of the 'files' file
 #------------------------------------------------------------------------------
 
-[ -d $MakeDir ] || {
-    echo "$Script error: '$MakeDir' directory does not exist in $PWD" 1>&2
-    exit 1
+unset dir
+MakeDir=Make
+
+expandpath()
+{
+    dir=`dirname $1`
+    cwd=$PWD
+    cd $dir
+    exPath=$PWD
+    cd $cwd
 }
+
+find_target()
+{
+    expandpath $1
+
+    if [ "$exPath" = "$WM_PROJECT_DIR" -o "$exPath" = "$HOME" -o "$exPath" = "/" ]
+    then
+        echo "$Script error: could not find Make directory"
+    elif [ -d "$1/Make" ]; then
+        echo "    Found target directory " $1
+        dir=$1
+    else
+        find_target "$1/.."
+    fi
+}
+
+if [ ! -d $MakeDir ]
+then
+    echo "$Script: '$MakeDir' directory does not exist in $PWD" 1>&2
+    echo "    Searching up directories tree for Make directory"
+
+    find_target .
+    makeType=
+
+    if [ "$dir" ]
+    then
+        cd $dir 2>/dev/null || {
+            echo "$Script error: could not change to directory '$dir'" 1>&2
+            exit 1
+        }
+    fi
+fi
+
 
 [ -r $MakeDir/files ] || {
     echo "$Script error: file '$MakeDir/files' does not exist in $PWD" 1>&2
     exit 1
 }
+
+
+#------------------------------------------------------------------------------
+# Transform options
+#------------------------------------------------------------------------------
 
 # transform "all" or no option to "libso" if that looks appropriate or remove it
 # so that the call to make builds the application
@@ -214,8 +263,11 @@ then
 fi
 
 
+#------------------------------------------------------------------------------
 # Spawn a sub-shell and unset MAKEFLAGS in that sub-shell to avoid
 # files and options being built in parallel
+#------------------------------------------------------------------------------
+
 (
     cd $MakeDir
     unset MAKEFLAGS
@@ -244,7 +296,7 @@ OBJECTS_DIR=$MakeDir/$WM_OPTIONS
 touch $OBJECTS_DIR/dontIncludeDeps
 
 case "$makeType" in
-lib | libo | libso )
+lib | libo | libso | dep )
     $make -s -f $WM_DIR/Makefile MAKE_DIR=$MakeDir INCLUDE_DEPS=$OBJECTS_DIR/dontIncludeDeps lnInclude/uptodate
     ;;
 esac
@@ -254,12 +306,16 @@ $make -s -f $WM_DIR/Makefile MAKE_DIR=$MakeDir INCLUDE_DEPS=$OBJECTS_DIR/dontInc
 rc=$?
 [ $rc -eq 0 ] || exit $rc
 
+
 #------------------------------------------------------------------------------
-# make the object files and link
+# Make the object files and link
 #------------------------------------------------------------------------------
 
-cmd="$make -f $WM_DIR/Makefile MAKE_DIR=$MakeDir INCLUDE_DEPS=$OBJECTS_DIR/includeDeps $makeType"
-# echo "cmd=$cmd"
-exec $cmd
+if [ "$makeType" != dep ]
+then
+    cmd="$make -f $WM_DIR/Makefile MAKE_DIR=$MakeDir INCLUDE_DEPS=$OBJECTS_DIR/includeDeps $makeType"
+    # echo "cmd=$cmd"
+    exec $cmd
+fi
 
 #------------------------------------------------------------------------------
